name: RAG CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
  
  build-push:
    needs: lint-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/rag-app:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/rag-app:${{ github.sha }}

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
    - name: SSH Deploy
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/rag-app:latest
          docker stop rag-app || true
          docker rm rag-app || true
          docker run -d \
            --name rag-app \
            -p 8000:8000 \
            -v /law_db:/app/data \
            ${{ secrets.DOCKER_HUB_USERNAME }}/rag-app:latest
